module.exports = {
  highlight: "highlight",
  audition_tag: "audition_tag",
  applicant: "applicant",
  role: "role",
  audition: "audition",
  messages: "messages",
  user: "user",
  requirement: "requirement",
  physical_attribute: "physical_attribute",
  voice_attribute: "voice_attribute",

  // No Foreign Key
  user_type: "user_type",
  city: "city",
  highlight_type: "highlight_type",
  eye_color: "eye_color",
  hair_color: "hair_color",
  gender: "gender",
  ethnicity: "ethnicity",
  body_type: "body_type",
  voice_type: "voice_type",
  audition_type: "audition_type",
  tag: "tag",
  role_type: "role_type",
};
